name: Build React Native Expo App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Ensure Expo project exists
        run: |
          if [ ! -f "package.json" ]; then
            echo "⚠️ No package.json found, creating a new Expo app..."
            npx create-expo-app@latest . --yes
          else
            echo "✅ Found package.json, using existing project."
          fi

      - name: Install dependencies
        run: npm install -g expo-cli && npm install

      - name: Start Expo server (QR Code)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          CI=1 npx expo start --tunnel > expo_output.txt 2>&1 &
          sleep 60
          grep -o "exp://[^\s]*" expo_output.txt | head -n 1 > expo_output.json || echo '{"url":null}' > expo_output.json

      - name: Upload Expo URL
        uses: actions/upload-artifact@v4
        with:
          name: expo-output
          path: expo_output.json
