name: Build React Native Expo App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Ensure Expo project exists
        run: |
          if [ ! -f "package.json" ]; then
            echo "⚠️ No package.json found, creating a new Expo app..."
            npx create-expo-app@latest . --yes
          else
            echo "✅ Found package.json, using existing project."
          fi

      - name: Install dependencies
        run: npm install -g expo-cli && npm install

      - name: Start Expo server (QR Code)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          set -o pipefail
          npx expo whoami || true
          # Start expo in background and capture full output
          npm install -g @expo/ngrok@^4.1.0 
          CI=1 npx expo start --tunnel --json > expo_output.txt 2>&1 &
          # wait up to 2 minutes for the URL to appear (poll every 5s)
          for i in {1..24}; do
            if grep -Eo 'exp://[^[:space:]]+' expo_output.txt || grep -Eo 'https?://[^[:space:]]*expo.dev[^[:space:]]*' expo_output.txt; then
              break
            fi
            sleep 5
          done
          echo "---- EXPO OUTPUT (tail) ----"
          tail -n 200 expo_output.txt || true
          # Try multiple patterns to find a usable URL
          # Try multiple patterns to find a usable URL
          URL=$(grep -Eo '"url":"[^"]+"' expo_output.txt | head -n1 | cut -d'"' -f4 || true)
          if [ -z "$URL" ]; then
            URL=$(grep -Eo 'exp://[^[:space:]]+' expo_output.txt | head -n1 || true)
          fi
          if [ -z "$URL" ]; then
            URL=$(grep -Eo 'https?://[^[:space:]]*expo.dev[^[:space:]]*' expo_output.txt | head -n1 || true)
          fi
          if [ -z "$URL" ]; then
            echo '{"url":null}' > expo_output.json
            echo "No expo URL found"
          else
            printf '{"url":"%s"}' "$URL" > expo_output.json
            echo "FOUND_EXPO_URL=$URL"
          fi

      - name: Upload Expo output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: expo-output
          path: |
            expo_output.json
            expo_output.txt
